CI: avoid failure on race
It's ok if the job does not push.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -40,6 +40,9 @@ jobs:
         if [ $MERGE_BRANCH_REF == main ]; then
           git config user.name "Contiki-NG CI"
           git config user.email nobody@contiki-ng.org
+          # Pull so the window for other jobs pushing is minimal.
+          git pull
           git commit -a -m "CI: update data"
-          git push
+          # Push, but mask failure and just avoid pushing on failure.
+          git push || (echo "Push failed, ignoring" && true)
         fi
